### PR TITLE
bugfix: ".txt" files

### PR DESCRIPTION
**Pull request by billiegoose**
For some reason .txt files weren't working. I think it's because this class just wasn't named correctly? Let me know what you think. Great library!

### CODE REVIEW

**Comment by Alhadis** [comment]
[See here](https://github.com/file-icons/atom/blob/ab518a896bf61045cdcf9573e0a48f43b80a4d41/config.cson#L66-L67):

> By default, icon names are suffixed with "-icon". Set `noSuffix` to true if you need to specify an icon class in its entirety (such as a default Atom icon). This should otherwise rarely be used.

Atom has a number of built-in icon-classes which the `file-icons` package also uses (although only a few icons are used this way). Search for `noSuffix` in [the package's main config file](https://github.com/file-icons/atom/blob/master/config.cson) for similar examples.

**Comment by billiegoose** [comment]
@Alhadis ok... does that impact the pull request? What should I change?

**Comment by Alhadis** [comment]
No change needed. It was just FYI.

**Comment by websemantics** [comment]
Thanks @wmhilton for your PR,

A similar [issue](https://github.com/websemantics/file-icons-js/issues/1) with other file types confirms @Alhadis's feedback, many thanks for that!

I'll check if it's better to import Atom's built-in icons or renaming to existing ones are the way to go.

**Comment by Alhadis** [comment]
FYI, I intend to restructure a lot of the code you're currently using. File-icons v2.2 will bring some hefty changes to its infrastructure.

Just a heads up.

**Comment by billiegoose** [comment]
Awesome stuff. I really appreciate being able to use Atom's file-icons in the browser. Thanks guys!

**Comment by tcosentino** [comment]
FYI @wmhilton I added a PR with these changes and a fix for pdf #3 

Thank you for this!

**Pull request merged**
